apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-nfs
  labels:
    app: filebrowser-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser-nfs
  template:
    metadata:
      labels:
        app: filebrowser-nfs
    spec:
      containers:
      - name: filebrowser-nfs
        image: hurlenko/filebrowser
        ports:
        - containerPort: 8080
          protocol: TCP
        name: http
        volumeMounts:
        - mountPath: data
          name: data1
      volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: demo-pvc
