apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  labels:
    app: demo
    pvc: demo
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-nfs
  labels:
    app: filebrowser-nfs
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: filebrowser-nfs
  type: LoadBalancer
